---
on:
  push:
    branches:
      - master

name: Deployment (prod)

jobs:
  build:
    name: Build and deploy assets (prod)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Get yarn cache directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-

      - name: Install yarn packages
        run: docker run -v $PWD:/app:rw -v ${{ steps.yarn-cache.outputs.dir }}:/usr/local/share/.cache/yarn/v6:rw itkdev/yarn:14 install

      - name: Build assets
        run: docker run -v $PWD:/app:rw -v ${{ steps.yarn-cache.outputs.dir }}:/usr/local/share/.cache/yarn/v6:rw itkdev/yarn:14 build

      - name: Sync assets to remote server
        uses: itk-dev/actions-rsync@master
        with:
          src: public/build
          dest: ${{ secrets.APP_PATH_PROD }}/public/
          host: ${{ secrets.HOST_PROD }}
          key: ${{ secrets.PRIVATE_KEY }}
          cert: ${{ secrets.PUBLIC_KEY_CERT }}

  remote:
    needs: build
    name: Deploy Application (prod)
    runs-on: ubuntu-latest
    steps:
      - name: Run remote commands
        uses: itk-dev/actions-remote-ssh@master
        with:
          command: |
            cd ${{ secrets.APP_PATH_PROD }}
            git clean -d --force
            git checkout master
            git fetch
            git reset origin/master --hard
            composer dump-env prod
            composer install --no-dev --optimize-autoloader
            bin/console doctrine:migrations:migrate --no-interaction
            bin/console doctrine:schema:validate
            APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
          host: ${{ secrets.HOST_PROD }}
          key: ${{ secrets.PRIVATE_KEY }}
          cert: ${{ secrets.PUBLIC_KEY_CERT }}
